### ISSUE TITLE
error

### ISSUE THREAD

**Issue by vcjuliocesar** [r-everse/linkedin-php#3]
An uncaught Exception was encountered

Type: League\OAuth2\Client\Provider\Exception\IdentityProviderException

Message: Unable to retrieve access token: appid/redirect uri/code verifier does not match authorization code. Or authorization code expired. Or external member binding exists

**Comment by ddonnini** [comment]
Hi there,
can you provide some more code, the authentication part maybe? It could be something related to your specific implementation, have you googled the error you get? Maybe this could help you: https://stackoverflow.com/questions/29804501/linkedin-oauth2-authorization-code-error

Otherwise, let's see some of your code, the authentication part of it :)

Thanks

**Comment by giovannialbero1992** [comment]
Hi @vcjuliocesar, I think that you are using the `initToken` method after you have stored the token.
When you perform authentication on LinkedIn in a second time, you must save token and expire timestamp in your store and after you can use token like the next example.

```php
$token = new AccessToken([
  'access_token' => $linkedinToken, //retrieved by $_GET['code'] before
  'expires_in' => $linkedinTokenExpiration, //timestamp expiration
]);
$linkedInClient->setToken($token);
```
